development:
  adapter: postgresql
  encoding: utf-8
  database: chefly2_api_development
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: utf-8
  database: chefly2_api_development
  pool: 5
  host: localhost